import { NgModule } from '@angular/core';
import {
  MdButtonModule,
  MdCheckboxModule,
  MdMenuModule,
  MdListModule,
  MdIconModule,
  MdToolbarModule,
  MdExpansionModule,
  MdFormFieldModule,
  MdInputModule,
  MdCardModule,
  MdProgressSpinnerModule,
  MdSlideToggleModule,
  MdSelectModule,
} from '@angular/material';

@NgModule({
  imports: [
    MdButtonModule,
    MdCheckboxModule,
    MdMenuModule,
    MdListModule,
    MdIconModule,
    MdToolbarModule,
    MdExpansionModule,
    MdFormFieldModule,
    MdInputModule,
    MdCardModule,
    MdProgressSpinnerModule,
    MdSlideToggleModule,
    MdSelectModule,
  ],
  exports: [
    MdButtonModule,
    MdCheckboxModule,
    MdMenuModule,
    MdListModule,
    MdIconModule,
    MdToolbarModule,
    MdExpansionModule,
    MdFormFieldModule,
    MdInputModule,
    MdCardModule,
    MdProgressSpinnerModule,
    MdSlideToggleModule,
    MdSelectModule,
  ],
})
export class MaterialComponentsModule {}
